### ISSUE TITLE
i have problem

### ISSUE THREAD

**Issue by seperto** [ubiq/ubiqsmart#305]
i used redshift to transfer wubq to polygon but i dont recieved 129 wubq to my wallet
my wallet is 0x6F455D217A7e3D256AA3b4386219Ed853e521E73
Hash
0x723ff2cb76aa7d2ddd3db8f435f48dec4d29d9b0d7fdf1e30c8a8bc9f271d27e
![Web capture_28-10-2022_25226_redshift ubiqsmart com](https://user-images.githubusercontent.com/116853866/198424803-efa871af-4e9f-4608-87b3-268103142075.jpeg)

**Comment by seperto** [comment]
@jyap808 @aldoborrero @iquidus @bitterlox @

**Comment by jyap808** [comment]
Use Ubiq Discord for any assistance 

https://discord.gg/ubiq

**Comment by seperto** [comment]
> 

i cant enter the ubiq discord buz there are problem  with verification
![Untitled](https://user-images.githubusercontent.com/116853866/198499255-6b5f266b-3312-4152-8baa-10162c7b8271.jpg)
